<?php
// attendance.php - API-First Version
require_once 'auth.php';
require_login();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Warzone Gym CRM - Attendance</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <script>
        tailwind.config = { theme: { extend: { colors: { primary: '#1a1a2e', secondary: '#16213e', accent: '#0f3460', highlight: '#e94560' } } } }
    </script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap');
        body { font-family: 'Outfit', sans-serif; background-color: #f8f9fa; }
        .calendar-grid { display: grid; grid-template-columns: repeat(7, 1fr); gap: 0.75rem; }
        .calendar-day { 
            aspect-ratio: 1; 
            display: flex; flex-direction: column; align-items: center; justify-content: center; 
            background: white; border-radius: 1rem; border: 1px solid #f1f5f9; cursor: pointer; transition: all 0.2s; 
        }
        .calendar-day:hover:not(.empty) { transform: translateY(-3px); box-shadow: 0 10px 15px -3px rgba(0,0,0,0.05); border-color: #e2e8f0; }
        .day-present { background: #f0fdf4; border-color: #22c55e; }
        .day-rest { background: #eff6ff; border-color: #3b82f6; }
        .day-absent { background: #fef2f2; border-color: #ef4444; }
        .day-today { background: #fee2e2; border-color: #e94560; border-width: 2px; }
        .dot { width: 6px; height: 6px; border-radius: 50%; margin-top: 4px; }
        .modal { display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.5); z-index: 1000; justify-content: center; align-items: center; }
        .modal-content { background: white; border-radius: 1.5rem; width: 100%; max-width: 400px; padding: 2rem; text-align: center; }
        .btn-status { padding: 1rem; border-radius: 1rem; font-weight: bold; transition: all 0.2s; width: 100%; display: flex; align-items: center; justify-content: center; gap: 0.5rem; }
        .btn-status:hover { transform: scale(1.02); }
    </style>
</head>
<body class="bg-gray-50 flex flex-col min-h-screen">
    <?php include 'includes/user_nav.php'; ?>

    <main class="container mx-auto px-4 py-8 flex-grow">
        <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-8">
            <div>
                <h2 class="text-3xl font-bold text-gray-800">Attendance Tracker</h2>
                <p class="text-gray-500">Consistency is the bridge between goals and accomplishment.</p>
            </div>
            <div id="attendanceStats" class="bg-white px-6 py-4 rounded-2xl shadow-sm border border-gray-100 text-center">
                <span class="block text-2xl font-black text-highlight" id="rateValue">--%</span>
                <span class="text-xs font-bold text-gray-400 uppercase tracking-widest">Global Rate</span>
            </div>
        </div>

        <div class="bg-white rounded-3xl shadow-xl p-8 max-w-4xl mx-auto border border-gray-100">
            <!-- Header Nav -->
            <div class="flex justify-between items-center mb-8">
                <div class="flex items-center space-x-4">
                    <button onclick="changeMonth(-1)" class="w-10 h-10 rounded-full bg-gray-50 flex items-center justify-center hover:bg-gray-100 transition"><i class="fas fa-chevron-left"></i></button>
                    <h3 class="text-xl font-black text-gray-800" id="monthDisplay">Month Year</h3>
                    <button onclick="changeMonth(1)" class="w-10 h-10 rounded-full bg-gray-50 flex items-center justify-center hover:bg-gray-100 transition"><i class="fas fa-chevron-right"></i></button>
                </div>
                <button onclick="goToToday()" class="text-xs font-bold text-highlight uppercase tracking-widest hover:underline">Go to Today</button>
            </div>

            <div class="calendar-grid text-gray-400 text-center text-xs font-bold mb-4 uppercase tracking-tighter">
                <div>Sun</div><div>Mon</div><div>Tue</div><div>Wed</div><div>Thu</div><div>Fri</div><div>Sat</div>
            </div>
            <div id="calendarDays" class="calendar-grid">
                <!-- Days generated by JS -->
            </div>
        </div>

        <div class="mt-8 grid grid-cols-2 md:grid-cols-4 gap-4 max-w-4xl mx-auto">
            <div class="bg-white p-4 rounded-2xl border border-gray-100 flex items-center space-x-3">
                <div class="w-3 h-3 bg-green-500 rounded-full"></div>
                <span class="text-sm font-bold text-gray-600">Present</span>
            </div>
            <div class="bg-white p-4 rounded-2xl border border-gray-100 flex items-center space-x-3">
                <div class="w-3 h-3 bg-blue-500 rounded-full"></div>
                <span class="text-sm font-bold text-gray-600">Rest Day</span>
            </div>
            <div class="bg-white p-4 rounded-2xl border border-gray-100 flex items-center space-x-3">
                <div class="w-3 h-3 bg-red-500 rounded-full"></div>
                <span class="text-sm font-bold text-gray-600">Missed</span>
            </div>
            <div class="bg-white p-4 rounded-2xl border border-gray-100 flex items-center space-x-3">
                <div class="w-3 h-3 bg-highlight rounded-full"></div>
                <span class="text-sm font-bold text-gray-600">Today</span>
            </div>
        </div>
    </main>

    <!-- Mark Attendance Modal -->
    <div id="attendanceModal" class="modal">
        <div class="modal-content shadow-2xl border border-gray-100">
            <h3 class="text-2xl font-black text-gray-800 mb-2" id="modalDate">Jan 1, 2026</h3>
            <p class="text-gray-400 font-medium mb-8">Mark your status for this day</p>
            <div class="space-y-4">
                <button onclick="submitStatus(1)" class="btn-status bg-green-50 text-green-600 hover:bg-green-100">
                    <i class="fas fa-check-circle"></i> I Trained Hard
                </button>
                <button onclick="submitStatus(-1)" class="btn-status bg-blue-50 text-blue-600 hover:bg-blue-100">
                    <i class="fas fa-bed"></i> Planned Rest
                </button>
                <button onclick="submitStatus(0)" class="btn-status bg-red-50 text-red-600 hover:bg-red-100">
                    <i class="fas fa-times-circle"></i> Missed Session
                </button>
                <button onclick="closeModal()" class="w-full py-4 text-gray-400 font-bold hover:text-gray-600">Cancel</button>
            </div>
        </div>
    </div>

    <script>
        let currentMonth = new Date().getMonth() + 1;
        let currentYear = new Date().getFullYear();
        let selectedDate = null;
        let records = {};

        async function fetchAttendance() {
            try {
                const response = await fetch(`api/attendance.php?month=${currentMonth}&year=${currentYear}`);
                const res = await response.json();
                if (res.status === 'success') {
                    records = {};
                    res.data.history.forEach(r => records[r.date] = parseInt(r.attended));
                    renderCalendar();
                }
            } catch (err) { console.error(err); }
        }

        function renderCalendar() {
            const container = document.getElementById('calendarDays');
            const monthDisplay = document.getElementById('monthDisplay');
            const date = new Date(currentYear, currentMonth - 1, 1);
            monthDisplay.innerText = date.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
            
            const firstDay = new Date(currentYear, currentMonth - 1, 1).getDay();
            const daysInMonth = new Date(currentYear, currentMonth, 0).getDate();
            const todayStr = new Date().toISOString().split('T')[0];

            container.innerHTML = '';

            // Padding
            for (let i = 0; i < firstDay; i++) container.innerHTML += '<div class="calendar-day empty border-none bg-transparent"></div>';

            for (let day = 1; day <= daysInMonth; day++) {
                const dateStr = `${currentYear}-${String(currentMonth).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
                const status = records[dateStr];
                let classList = "calendar-day";
                if (dateStr === todayStr) classList += " day-today";
                if (status === 1) classList += " day-present";
                if (status === -1) classList += " day-rest";
                if (status === 0) classList += " day-absent";

                container.innerHTML += `
                    <div class="${classList}" onclick="openModal('${dateStr}')">
                        <span class="text-sm font-black ${status !== undefined ? 'text-gray-800' : 'text-gray-400'}">${day}</span>
                        ${status === 1 ? '<div class="dot bg-green-500"></div>' : ''}
                        ${status === -1 ? '<div class="dot bg-blue-500"></div>' : ''}
                        ${status === 0 ? '<div class="dot bg-red-500"></div>' : ''}
                    </div>
                `;
            }
        }

        function changeMonth(delta) {
            currentMonth += delta;
            if (currentMonth > 12) { currentMonth = 1; currentYear++; }
            if (currentMonth < 1) { currentMonth = 12; currentYear--; }
            fetchAttendance();
        }

        function goToToday() {
            currentMonth = new Date().getMonth() + 1;
            currentYear = new Date().getFullYear();
            fetchAttendance();
        }

        function openModal(date) {
            selectedDate = date;
            document.getElementById('modalDate').innerText = new Date(date).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
            document.getElementById('attendanceModal').style.display = 'flex';
        }

        function closeModal() { document.getElementById('attendanceModal').style.display = 'none'; }

        async function submitStatus(status) {
            const formData = new FormData();
            formData.append('date', selectedDate);
            formData.append('attended', status);
            formData.append('csrf_token', '<?= csrf_token() ?>');

            try {
                const response = await fetch('api/attendance.php', { method: 'POST', body: formData });
                const res = await response.json();
                if (res.status === 'success') {
                    closeModal();
                    fetchAttendance();
                }
            } catch (err) { console.error(err); }
        }

        document.addEventListener('DOMContentLoaded', fetchAttendance);
    </script>
    <?php include 'modal_logout.php'; ?>
</body>
</html>