<?php
// includes/dashboard/activity_sidebar.php - API-First Version
?>
<div class="space-y-6">
    <div class="bg-white rounded-3xl shadow-sm border border-gray-100 overflow-hidden">
        <div class="p-6 border-b border-gray-50">
            <h3 class="text-xl font-bold text-gray-800">Insights Feed</h3>
            <p class="text-xs font-bold text-gray-400 uppercase tracking-widest">Real-time Activity</p>
        </div>
        <div class="p-6">
            <div id="activitySkeleton" class="space-y-4">
                <?php for($i=0; $i<3; $i++): ?>
                    <div class="h-16 bg-gray-50 rounded-2xl animate-pulse"></div>
                <?php endfor; ?>
            </div>
            
            <div id="activityFeed" class="space-y-4 hidden">
                <!-- Activities generated by JS -->
            </div>
        </div>
    </div>

    <!-- Upgrade Card -->
    <div class="bg-primary text-white p-8 rounded-3xl shadow-xl overflow-hidden relative group">
        <div class="absolute -right-6 -bottom-6 opacity-10 transform group-hover:scale-125 transition-transform duration-700">
            <i class="fas fa-crown text-[8rem]"></i>
        </div>
        <div class="relative z-10">
            <h4 class="text-xl font-black mb-2">Warzone Pro</h4>
            <p class="text-xs text-gray-400 font-medium mb-6 leading-relaxed">Unlock biometric analytics, custom hormone-optimized meal plans, and video form correction.</p>
            <button class="w-full bg-highlight py-3 rounded-2xl text-sm font-black shadow-lg hover:opacity-90 transition">
                UPGRADE NOW
            </button>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', async () => {
    const feed = document.getElementById('activityFeed');
    const skeleton = document.getElementById('activitySkeleton');
    
    try {
        const response = await fetch('api/activity.php?limit=5');
        const res = await response.json();
        
        if (res.status === 'success' && res.data.activities.length > 0) {
            feed.innerHTML = res.data.activities.map(act => {
                const type = act.type.toLowerCase();
                let icon = 'fas fa-info-circle';
                let color = 'gray';
                
                if (type.includes('workout')) { icon = 'fas fa-dumbbell'; color = 'highlight'; }
                else if (type.includes('attendance')) { icon = 'fas fa-calendar-check'; color = 'success'; }
                else if (type.includes('journal')) { icon = 'fas fa-book-open'; color = 'blue-500'; }

                return `
                    <div class="flex items-start p-4 bg-gray-50 rounded-2xl border-l-4 border-${color}">
                        <div class="mr-4 mt-1">
                            <i class="${icon} text-${color} text-sm"></i>
                        </div>
                        <div class="flex-1 min-w-0">
                            <div class="flex justify-between items-start mb-0.5">
                                <h4 class="font-bold text-xs text-gray-800 truncate">${act.type}</h4>
                                <span class="text-[9px] font-bold text-gray-400 uppercase ml-2">${timeAgo(act.created_at)}</span>
                            </div>
                            <p class="text-[11px] text-gray-500 leading-tight">${act.details}</p>
                        </div>
                    </div>
                `;
            }).join('');
            
            skeleton.classList.add('hidden');
            feed.classList.remove('hidden');
        } else {
            feed.innerHTML = `
                <div class="text-center py-10">
                    <i class="fas fa-ghost text-3xl text-gray-100 mb-2"></i>
                    <p class="text-xs font-bold text-gray-400">Nothing to show yet.</p>
                </div>
            `;
            skeleton.classList.add('hidden');
            feed.classList.remove('hidden');
        }
    } catch (err) { console.error('Activity error:', err); }
});

function timeAgo(date) {
    const seconds = Math.floor((new Date() - new Date(date)) / 1000);
    if (seconds < 60) return 'Just now';
    const minutes = Math.floor(seconds / 60);
    if (minutes < 60) return minutes + 'm';
    const hours = Math.floor(minutes / 60);
    if (hours < 24) return hours + 'h';
    return Math.floor(hours / 24) + 'd';
}
</script>
