<?php
// includes/dashboard/attendance_calendar.php - API-First Version
?>
<div class="bg-white rounded-3xl shadow-sm border border-gray-100 overflow-hidden">
    <div class="p-6 border-b border-gray-50 flex items-center justify-between">
        <div>
            <h3 class="text-xl font-bold text-gray-800">Attendance</h3>
            <p class="text-xs font-bold text-gray-400 uppercase tracking-widest">Monthly Progress</p>
        </div>
        <a href="attendance.php" class="text-highlight hover:underline font-bold text-xs uppercase tracking-widest">
            Detailed Log
        </a>
    </div>

    <div class="p-6">
        <!-- Calendar Grid -->
        <div id="calendarSkeleton" class="grid grid-cols-7 gap-2">
            <?php for($i=0; $i<35; $i++): ?>
                <div class="h-10 bg-gray-50 rounded-lg animate-pulse"></div>
            <?php endfor; ?>
        </div>
        
        <div id="calendarGrid" class="grid grid-cols-7 gap-2 hidden">
            <!-- Days generated by JS -->
        </div>
        
        <div class="mt-6 flex items-center justify-center space-x-6">
            <div class="flex items-center space-x-2">
                <div class="w-2 h-2 rounded-full bg-green-500"></div>
                <span class="text-[10px] font-bold text-gray-400 uppercase tracking-tighter">Present</span>
            </div>
            <div class="flex items-center space-x-2">
                <div class="w-2 h-2 rounded-full bg-blue-500"></div>
                <span class="text-[10px] font-bold text-gray-400 uppercase tracking-tighter">Rest Day</span>
            </div>
            <div class="flex items-center space-x-2">
                <div class="w-2 h-2 rounded-full bg-red-500"></div>
                <span class="text-[10px] font-bold text-gray-400 uppercase tracking-tighter">Missed</span>
            </div>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', async () => {
    const grid = document.getElementById('calendarGrid');
    const skeleton = document.getElementById('calendarSkeleton');
    
    try {
        const response = await fetch('api/attendance.php');
        const res = await response.json();
        
        if (res.status === 'success') {
            const records = {};
            res.data.history.forEach(r => records[new Date(r.date).getDate()] = parseInt(r.attended));
            
            const today = new Date();
            const firstDay = new Date(today.getFullYear(), today.getMonth(), 1).getDay();
            const daysInMonth = new Date(today.getFullYear(), today.getMonth() + 1, 0).getDate();
            
            grid.innerHTML = '';
            
            // Padding
            for (let i = 0; i < firstDay; i++) {
                grid.innerHTML += '<div class="h-10"></div>';
            }
            
            // Days
            for (let day = 1; day <= daysInMonth; day++) {
                const status = records[day];
                let classList = "h-10 flex flex-col items-center justify-center rounded-xl transition-all text-sm font-bold ";
                let dotClass = "";
                
                if (status === 1) { classList += "bg-green-50 text-green-600"; dotClass = "bg-green-500"; }
                else if (status === -1) { classList += "bg-blue-50 text-blue-600"; dotClass = "bg-blue-500"; }
                else if (status === 0) { classList += "bg-red-50 text-red-600"; dotClass = "bg-red-500"; }
                else { classList += "text-gray-400"; }
                
                if (day === today.getDate()) classList += " border-2 border-highlight";
                
                grid.innerHTML += `
                    <div class="${classList}">
                        ${day}
                        ${dotClass ? `<div class="w-1 h-1 rounded-full ${dotClass} mt-0.5"></div>` : ''}
                    </div>
                `;
            }
            
            skeleton.classList.add('hidden');
            grid.classList.remove('hidden');
        }
    } catch (err) {
        console.error('Calendar error:', err);
    }
});
</script>
